# Generated by Django 3.1.5 on 2021-04-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodePaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('code', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=True)),
                ('expiration', models.CharField(choices=[(0, 'Never'), (1, '10 min'), (2, '1 hr'), (3, '1 week'), (4, '2 week'), (5, '1 month'), (6, '6 month'), (7, '1 year')], default=0, max_length=3)),
                ('language', models.CharField(choices=[(0, 'PLAIN'), (1, 'PYTHON'), (2, 'JAVASCRIPT'), (3, 'GOLANG'), (4, 'RUBY'), (5, 'HTML'), (6, 'JAVA'), (7, 'JSON'), (8, 'CSS'), (9, 'C#'), (10, 'C++')], default=0, max_length=3)),
                ('syntax_highlighting', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.codefolder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
