# Generated by Django 3.1.5 on 2021-04-23 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefolder',
            name='folder_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
