# Generated by Django 3.1.5 on 2021-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_codefolder_folder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepaste',
            name='expiration',
            field=models.CharField(choices=[('0', 'Never'), ('1', '10 min'), ('2', '1 hr'), ('3', '1 week'), ('4', '2 week'), ('5', '1 month'), ('6', '6 month'), ('7', '1 year')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='codepaste',
            name='language',
            field=models.CharField(choices=[('0', 'PLAIN'), ('1', 'PYTHON'), ('2', 'JAVASCRIPT'), ('3', 'GOLANG'), ('4', 'RUBY'), ('5', 'HTML'), ('6', 'JAVA'), ('7', 'JSON'), ('8', 'CSS'), ('9', 'C#'), ('10', 'C++')], default='0', max_length=3),
        ),
    ]
