# Generated by Django 3.1.5 on 2021-05-18 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210506_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultSyntax', models.CharField(choices=[('PLAINTEXT', 'PLAINTEXT'), ('PYTHON', 'PYTHON'), ('JAVASCRIPT', 'JAVASCRIPT'), ('GOLANG', 'GOLANG'), ('RUBY', 'RUBY'), ('HTML', 'HTML'), ('JAVA', 'JAVA'), ('JSON', 'JSON'), ('CSS', 'CSS'), ('C#', 'C#'), ('C++', 'C++')], default='PLAINTEXT', max_length=30)),
                ('defaultExpiration', models.CharField(choices=[('Never', 'Never'), ('10 min', '10 min'), ('1 hr', '1 hr'), ('1 week', '1 week'), ('2 week', '2 week'), ('1 month', '1 month'), ('6 month', '6 month'), ('1 year', '1 year')], default='NEVER', max_length=30)),
                ('nightMode', models.BooleanField(default=True)),
                ('defaultExposure', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(blank=True, max_length=225, null=True)),
                ('location', models.CharField(blank=True, max_length=225, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
