# Generated by Django 3.1.5 on 2021-05-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepaste',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
